problem solved with database

diff --git a/Dockerized/DB/Dockerfile b/Dockerized/DB/Dockerfile
--- a/Dockerized/DB/Dockerfile
+++ b/Dockerized/DB/Dockerfile
@@ -1,6 +1,7 @@
 FROM mysql:8.4.0
 
+# Copy init.sql into the image
 COPY init.sql /docker-entrypoint-initdb.d/
-RUN echo "Uruchamianie skryptu init.sql..."
 
-# Dodaj resztę swoich instrukcji Dockerfile
+# Check if init.sql exists
+RUN test -e /docker-entrypoint-initdb.d/init.sql && { echo "init.sql found and copied successfully."; } || { echo "Error: init.sql not found!"; exit 1; }
